[project]
name = "sc-iceberg-api-weather-platform"
version = "0.2.1"
description = "POC: A data platform showcasing the use of Apache Iceberg for managing weather data ingestion and querying."
authors = [{ name = "Pepijn Schouten" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.12.20",
    "dagster-webserver>=1.12.20",
    "fastapi[standard]>=0.135.1",
    "httpx>=0.28.1",
    "pandas>=3.0.1",
    "pandera>=0.30.1",
    "pyiceberg[pyarrow,sql-sqlite]>=0.11.1",
    "pytest>=9.0.2",
    "tenacity>=9.1.4",
]

[dependency-groups]
dev = ["black>=26.3.1", "bump-my-version>=1.2.7", "click>=8.3.1"]

[tool.bumpversion]
current_version = "0.2.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
